# Setup
title:               MancityBallboy
tagline:             '흔적 남기기'
description:         '개발자를 꿈꾸는 강우의 흔적'
url:                 'https://yhnb3.github.io'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              엄강우
  url:               https://github.com/yhnb3
  email:             yhnb33@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
